name: Publish with docker

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  AZURE_WEB_APP_NAME: testtimeapiwithdocker

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}      

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./DeployAzureExample/Dockerfile
          push: true
          tags: ducware/dotnet-test:latest

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEB_APP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE_WITH_DOCKER }}
          images: 'ducware/dotnet-test:latest'
